# Generated by GitHub Copilot
from pathlib import Path

from fastapi.testclient import TestClient

from app.config import Settings
from app.main import app
from app.store import init_db


# Generated by GitHub Copilot
"""Build test app client with isolated sqlite path and permissive host allowlist."""
def create_test_client(tmp_path: Path) -> TestClient:
    db_path = tmp_path / "prompt_ops_test.sqlite3"
    init_db(str(db_path))

    from app import main as main_module

    main_module.settings = Settings(
        app_env="test",
        host="127.0.0.1",
        port=8020,
        allowed_hosts={"localhost", "127.0.0.1", "testserver"},
        cors_origins=["http://localhost:8100"],
        enable_hsts=False,
        max_payload_bytes=1024 * 1024,
        db_path=str(db_path),
    )

    return TestClient(app)


def test_health_endpoint(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/health", headers={"host": "testserver"})
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_prompt_and_experiment_flow(tmp_path: Path):
    client = create_test_client(tmp_path)

    baseline = client.post(
        "/api/v1/prompts",
        headers={"host": "testserver"},
        json={
            "name": "support_refund_prompt",
            "version": "v1",
            "content": "baseline prompt",
            "variables": ["region"],
            "tags": ["support"],
        },
    )
    challenger = client.post(
        "/api/v1/prompts",
        headers={"host": "testserver"},
        json={
            "name": "support_refund_prompt",
            "version": "v2",
            "content": "challenger prompt",
            "variables": ["region"],
            "tags": ["support"],
        },
    )

    assert baseline.status_code == 201
    assert challenger.status_code == 201

    experiment = client.post(
        "/api/v1/experiments",
        headers={"host": "testserver"},
        json={
            "name": "refund_flow_ab",
            "baseline_prompt_id": baseline.json()["prompt_id"],
            "challenger_prompt_id": challenger.json()["prompt_id"],
            "traffic_split_baseline": 0.5,
        },
    )
    assert experiment.status_code == 201

    experiment_id = experiment.json()["experiment_id"]

    eval_response = client.post(
        f"/api/v1/experiments/{experiment_id}/evaluate",
        headers={"host": "testserver"},
        json={
            "items": [
                {
                    "variant": "baseline",
                    "quality_score": 0.75,
                    "latency_ms": 910,
                    "safety_pass": True,
                },
                {
                    "variant": "challenger",
                    "quality_score": 0.84,
                    "latency_ms": 800,
                    "safety_pass": True,
                },
            ]
        },
    )

    assert eval_response.status_code == 200
    assert eval_response.json()["winner_variant"] in {"baseline", "challenger", None}

    promote_response = client.post(
        f"/api/v1/experiments/{experiment_id}/promote",
        headers={"host": "testserver"},
    )

    assert promote_response.status_code in {200, 409}


def test_host_guard(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/health", headers={"host": "blocked.example"})
    assert response.status_code == 400
    assert response.json()["error"] == "host_not_allowed"
