# Generated by GitHub Copilot
from dataclasses import replace
from pathlib import Path

from fastapi.testclient import TestClient

from app import main as main_module
from app.config import Settings
from app.main import app
from app.store import init_db


# Generated by GitHub Copilot
"""Build test app client with isolated sqlite path and permissive host allowlist."""
def create_test_client(tmp_path: Path, rate_limit_per_minute: int = 120) -> TestClient:
    db_path = tmp_path / "prompt_ops_test.sqlite3"
    init_db(str(db_path))

    from app import main as main_module

    main_module.settings = Settings(
        app_env="test",
        host="127.0.0.1",
        port=8020,
        allowed_hosts={"localhost", "127.0.0.1", "testserver"},
        cors_origins=["http://localhost:8100"],
        enable_hsts=False,
        max_payload_bytes=1024 * 1024,
        rate_limit_per_minute=rate_limit_per_minute,
        db_path=str(db_path),
        api_key="",
    )
    main_module.rate_limiter.clear()

    return TestClient(app)


# Generated by GitHub Copilot
def _assert_error_contract(
    response,
    expected_status: int,
    expected_code: str,
    expected_message: str | None = None,
    expect_details: bool = False,
) -> None:
    """Validate normalized FastAPI error envelopes for contract assertions."""
    assert response.status_code == expected_status
    payload = response.json()
    assert isinstance(payload.get("error"), dict)
    assert payload["error"]["code"] == expected_code
    assert isinstance(payload["error"]["message"], str)
    if expected_message is not None:
        assert payload["error"]["message"] == expected_message
    assert isinstance(payload["error"]["request_id"], str)
    assert payload["error"]["request_id"]
    if expect_details:
        assert "details" in payload["error"]


def test_health_endpoint(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/health", headers={"host": "testserver"})
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


def test_probe_alias_endpoints(tmp_path: Path):
    client = create_test_client(tmp_path)

    health_alias = client.get("/healthz", headers={"host": "testserver"})
    assert health_alias.status_code == 200
    assert health_alias.json()["status"] == "ok"

    ready_alias = client.get("/readyz", headers={"host": "testserver"})
    assert ready_alias.status_code == 200
    assert ready_alias.json()["status"] in {"ready", "not_ready"}


def test_prompt_and_experiment_flow(tmp_path: Path):
    client = create_test_client(tmp_path)

    baseline = client.post(
        "/api/v1/prompts",
        headers={"host": "testserver"},
        json={
            "name": "support_refund_prompt",
            "version": "v1",
            "content": "baseline prompt",
            "variables": ["region"],
            "tags": ["support"],
        },
    )
    challenger = client.post(
        "/api/v1/prompts",
        headers={"host": "testserver"},
        json={
            "name": "support_refund_prompt",
            "version": "v2",
            "content": "challenger prompt",
            "variables": ["region"],
            "tags": ["support"],
        },
    )

    assert baseline.status_code == 201
    assert challenger.status_code == 201

    experiment = client.post(
        "/api/v1/experiments",
        headers={"host": "testserver"},
        json={
            "name": "refund_flow_ab",
            "baseline_prompt_id": baseline.json()["prompt_id"],
            "challenger_prompt_id": challenger.json()["prompt_id"],
            "traffic_split_baseline": 0.5,
        },
    )
    assert experiment.status_code == 201

    experiment_id = experiment.json()["experiment_id"]

    eval_response = client.post(
        f"/api/v1/experiments/{experiment_id}/evaluate",
        headers={"host": "testserver"},
        json={
            "items": [
                {
                    "variant": "baseline",
                    "quality_score": 0.75,
                    "latency_ms": 910,
                    "safety_pass": True,
                },
                {
                    "variant": "challenger",
                    "quality_score": 0.84,
                    "latency_ms": 800,
                    "safety_pass": True,
                },
            ]
        },
    )

    assert eval_response.status_code == 200
    assert eval_response.json()["winner_variant"] in {"baseline", "challenger", None}

    promote_response = client.post(
        f"/api/v1/experiments/{experiment_id}/promote",
        headers={"host": "testserver"},
    )

    assert promote_response.status_code in {200, 409}


def test_host_guard(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/health", headers={"host": "blocked.example"})
    _assert_error_contract(
        response,
        expected_status=400,
        expected_code="host_not_allowed",
        expected_message="host_not_allowed",
    )


def test_error_responses_include_security_and_request_headers(tmp_path: Path):
    client = create_test_client(tmp_path)
    response = client.get("/api/v1/experiments/missing-exp", headers={"host": "testserver"})

    assert response.status_code == 404
    assert response.headers.get("X-Request-ID")
    assert response.headers.get("X-Content-Type-Options") == "nosniff"
    assert response.headers.get("X-Frame-Options") == "DENY"


def test_phase1_auth_required_contract(tmp_path: Path, monkeypatch):
    """Require API key on protected routes and return normalized unauthorized responses."""
    client = create_test_client(tmp_path)
    monkeypatch.setattr(main_module, "settings", replace(main_module.settings, api_key="phase1-secret"))

    unauthorized = client.get("/api/v1/prompts", headers={"host": "testserver"})
    _assert_error_contract(
        unauthorized,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    invalid_key = client.get("/api/v1/prompts", headers={"host": "testserver", "X-API-Key": "wrong"})
    _assert_error_contract(
        invalid_key,
        expected_status=401,
        expected_code="unauthorized",
        expected_message="api_key_invalid",
    )

    authorized = client.get("/api/v1/prompts", headers={"host": "testserver", "X-API-Key": "phase1-secret"})
    assert authorized.status_code == 200


def test_phase1_error_contract_response(tmp_path: Path):
    """Return normalized not-found payloads for unknown experiment access."""
    client = create_test_client(tmp_path)
    response = client.get("/api/v1/experiments/missing-exp", headers={"host": "testserver"})
    _assert_error_contract(
        response,
        expected_status=404,
        expected_code="not_found",
        expected_message="experiment_not_found",
    )


def test_rate_limit_enforcement_contract(tmp_path: Path):
    client = create_test_client(tmp_path, rate_limit_per_minute=1)

    first = client.get("/api/v1/prompts", headers={"host": "testserver"})
    assert first.status_code == 200

    second = client.get("/api/v1/prompts", headers={"host": "testserver"})
    _assert_error_contract(
        second,
        expected_status=429,
        expected_code="rate_limited",
        expected_message="rate_limited",
    )
    assert second.headers.get("Retry-After") == "60"
    assert second.headers.get("X-Request-ID")
