# Generated by GitHub Copilot
import os
from dataclasses import dataclass


@dataclass(frozen=True)
class Settings:
    app_env: str
    host: str
    port: int
    allowed_hosts: set[str]
    cors_origins: list[str]
    enable_hsts: bool
    max_payload_bytes: int
    db_path: str
    api_key: str


# Generated by GitHub Copilot
"""Parse comma-separated configuration values into a normalized list."""
def parse_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


# Generated by GitHub Copilot
"""Build immutable runtime settings from environment variables."""
def get_settings() -> Settings:
    return Settings(
        app_env=os.getenv("APP_ENV", "development"),
        host=os.getenv("PROMPT_OPS_HOST", "0.0.0.0"),
        port=int(os.getenv("PROMPT_OPS_PORT", "8020")),
        allowed_hosts=set(parse_csv(os.getenv("PROMPT_OPS_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver"))),
        cors_origins=parse_csv(
            os.getenv("PROMPT_OPS_CORS_ORIGINS", "http://localhost:8100,http://127.0.0.1:8100")
        ),
        enable_hsts=os.getenv("PROMPT_OPS_ENABLE_HSTS", "false").lower() == "true",
        max_payload_bytes=int(os.getenv("PROMPT_OPS_MAX_PAYLOAD_BYTES", "2097152")),
        db_path=os.getenv("PROMPT_OPS_DB_PATH", "./backend/data/prompt_ops.sqlite3"),
        api_key=os.getenv("PROMPT_OPS_API_KEY", "").strip(),
    )
