# Generated by GitHub Copilot
import os
from dataclasses import dataclass


@dataclass(frozen=True)
class Settings:
    app_env: str
    host: str
    port: int
    allowed_hosts: set[str]
    cors_origins: list[str]
    enable_hsts: bool
    max_payload_bytes: int
    rate_limit_per_minute: int
    db_path: str
    api_key: str


# Generated by GitHub Copilot
"""Parse comma-separated configuration values into a normalized list."""
def parse_csv(value: str) -> list[str]:
    return [item.strip() for item in value.split(",") if item.strip()]


# Generated by GitHub Copilot
"""Parse constrained integer settings from environment values."""
def parse_int(raw_value: str | None, default: int, min_value: int) -> int:
    if raw_value is None:
        return default
    try:
        parsed = int(raw_value)
    except ValueError:
        return default
    return max(min_value, parsed)


# Generated by GitHub Copilot
"""Parse boolean settings from environment values with safe defaults."""
def parse_bool(raw_value: str | None, default: bool) -> bool:
    if raw_value is None:
        return default
    lowered = raw_value.strip().lower()
    if lowered in {"1", "true", "yes", "on"}:
        return True
    if lowered in {"0", "false", "no", "off"}:
        return False
    return default


# Generated by GitHub Copilot
"""Build immutable runtime settings from environment variables."""
def get_settings() -> Settings:
    return Settings(
        app_env=os.getenv("APP_ENV", "development"),
        host=os.getenv("PROMPT_OPS_HOST", "0.0.0.0"),
        port=parse_int(os.getenv("PROMPT_OPS_PORT"), default=8020, min_value=1),
        allowed_hosts=set(parse_csv(os.getenv("PROMPT_OPS_ALLOWED_HOSTS", "localhost,127.0.0.1,testserver"))),
        cors_origins=parse_csv(
            os.getenv("PROMPT_OPS_CORS_ORIGINS", "http://localhost:8100,http://127.0.0.1:8100")
        ),
        enable_hsts=parse_bool(os.getenv("PROMPT_OPS_ENABLE_HSTS"), default=False),
        max_payload_bytes=parse_int(
            os.getenv("PROMPT_OPS_MAX_PAYLOAD_BYTES"),
            default=2_097_152,
            min_value=1024,
        ),
        rate_limit_per_minute=parse_int(
            os.getenv("PROMPT_OPS_RATE_LIMIT_PER_MINUTE"),
            default=120,
            min_value=10,
        ),
        db_path=os.getenv("PROMPT_OPS_DB_PATH", "./backend/data/prompt_ops.sqlite3"),
        api_key=os.getenv("PROMPT_OPS_API_KEY", "").strip(),
    )
