# Generated by GitHub Copilot
from fastapi import FastAPI, HTTPException, Request, Response, status
from fastapi.middleware.cors import CORSMiddleware

from .config import get_settings
from .middleware import apply_security_headers, is_allowed_host
from .models import (
    EvaluateExperimentRequest,
    EvaluateExperimentResponse,
    ExperimentCreateRequest,
    ExperimentSummary,
    PromptCreateRequest,
    PromptVersion,
)
from .service import build_experiment_row, build_prompt_row, evaluate_items
from .store import (
    create_experiment,
    create_prompt,
    db_ready,
    get_experiment,
    init_db,
    list_experiments,
    list_prompts,
    promote_experiment,
    prompt_exists,
    update_experiment_evaluation,
)

settings = get_settings()
init_db(settings.db_path)

app = FastAPI(title="prompt-ops", version="0.1.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_guards(request: Request, call_next):
    host_header = request.headers.get("host", "")
    if not is_allowed_host(host_header, settings.allowed_hosts):
        return Response(content='{"error":"host_not_allowed"}', media_type="application/json", status_code=400)

    if request.headers.get("content-length"):
        content_length = int(request.headers["content-length"])
        if content_length > settings.max_payload_bytes:
            return Response(content='{"error":"payload_too_large"}', media_type="application/json", status_code=413)

    response = await call_next(request)
    return apply_security_headers(response, settings.enable_hsts)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def ready(response: Response) -> dict[str, str]:
    if not db_ready(settings.db_path):
        response.status_code = status.HTTP_503_SERVICE_UNAVAILABLE
        return {"status": "not_ready"}
    return {"status": "ready"}


@app.post("/api/v1/prompts", response_model=PromptVersion, status_code=status.HTTP_201_CREATED)
def create_prompt_version(payload: PromptCreateRequest) -> dict:
    row = build_prompt_row(payload)
    return create_prompt(settings.db_path, row)


@app.get("/api/v1/prompts", response_model=list[PromptVersion])
def fetch_prompts() -> list[dict]:
    return list_prompts(settings.db_path)


@app.post("/api/v1/experiments", response_model=ExperimentSummary, status_code=status.HTTP_201_CREATED)
def create_experiment_entry(payload: ExperimentCreateRequest) -> dict:
    if not prompt_exists(settings.db_path, payload.baseline_prompt_id):
        raise HTTPException(status_code=404, detail="baseline_prompt_not_found")
    if not prompt_exists(settings.db_path, payload.challenger_prompt_id):
        raise HTTPException(status_code=404, detail="challenger_prompt_not_found")

    row = build_experiment_row(payload)
    return create_experiment(settings.db_path, row)


@app.get("/api/v1/experiments", response_model=list[ExperimentSummary])
def fetch_experiments() -> list[dict]:
    return list_experiments(settings.db_path)


@app.get("/api/v1/experiments/{experiment_id}")
def fetch_experiment(experiment_id: str) -> dict:
    row = get_experiment(settings.db_path, experiment_id)
    if not row:
        raise HTTPException(status_code=404, detail="experiment_not_found")
    return row


@app.post("/api/v1/experiments/{experiment_id}/evaluate", response_model=EvaluateExperimentResponse)
def evaluate_experiment(experiment_id: str, payload: EvaluateExperimentRequest) -> dict:
    row = get_experiment(settings.db_path, experiment_id)
    if not row:
        raise HTTPException(status_code=404, detail="experiment_not_found")

    evaluation = evaluate_items(payload)
    update_experiment_evaluation(
        settings.db_path,
        experiment_id,
        evaluation["baseline_score"],
        evaluation["challenger_score"],
        evaluation["confidence_gap"],
        evaluation["winner_variant"],
        payload.model_dump(),
    )

    return {
        "experiment_id": experiment_id,
        "baseline_score": evaluation["baseline_score"],
        "challenger_score": evaluation["challenger_score"],
        "winner_variant": evaluation["winner_variant"],
        "confidence_gap": evaluation["confidence_gap"],
    }


@app.post("/api/v1/experiments/{experiment_id}/promote")
def promote_experiment_winner(experiment_id: str) -> dict[str, str]:
    experiment = get_experiment(settings.db_path, experiment_id)
    if not experiment:
        raise HTTPException(status_code=404, detail="experiment_not_found")

    promoted = promote_experiment(settings.db_path, experiment_id)
    if not promoted:
        raise HTTPException(status_code=409, detail="winner_required_before_promotion")

    return {"status": "promoted"}
