# Generated by GitHub Copilot
from fastapi import Depends, FastAPI, Header, HTTPException, Request, Response, status
from fastapi.exceptions import RequestValidationError
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from starlette.exceptions import HTTPException as StarletteHTTPException
from uuid import uuid4

from .config import get_settings
from .middleware import apply_security_headers, is_allowed_host
from .models import (
    EvaluateExperimentRequest,
    EvaluateExperimentResponse,
    ExperimentCreateRequest,
    ExperimentSummary,
    PromptCreateRequest,
    PromptVersion,
)
from .service import build_experiment_row, build_prompt_row, evaluate_items
from .store import (
    create_experiment,
    create_prompt,
    db_ready,
    get_experiment,
    init_db,
    list_experiments,
    list_prompts,
    promote_experiment,
    prompt_exists,
    update_experiment_evaluation,
)

settings = get_settings()
init_db(settings.db_path)
AUTH_EXEMPT_PATHS = {
    "/",
    "/health",
    "/ready",
    "/healthz",
    "/readyz",
    "/docs",
    "/openapi.json",
    "/redoc",
}


# Generated by GitHub Copilot
def _request_id_from_request(request: Request) -> str:
    """Read request correlation id from request state or fallback headers."""
    request_id = getattr(request.state, "request_id", None)
    if isinstance(request_id, str) and request_id:
        return request_id
    return request.headers.get("X-Request-ID", "unknown")


# Generated by GitHub Copilot
def _build_error_payload(
    request: Request,
    code: str,
    message: str,
    details: object | None = None,
) -> dict[str, object]:
    """Build standardized error payloads for API clients."""
    payload: dict[str, object] = {
        "error": {
            "code": code,
            "message": message,
            "request_id": _request_id_from_request(request),
        }
    }
    if details is not None:
        payload["error"]["details"] = details
    return payload


# Generated by GitHub Copilot
def _status_to_error_code(status_code: int) -> str:
    """Map HTTP statuses to stable error contract codes."""
    mapping = {
        400: "bad_request",
        401: "unauthorized",
        403: "forbidden",
        404: "not_found",
        409: "conflict",
        413: "payload_too_large",
        422: "validation_error",
        429: "rate_limited",
    }
    if status_code >= 500:
        return "internal_error"
    return mapping.get(status_code, "request_failed")


# Generated by GitHub Copilot
def _require_api_key(
    request: Request,
    x_api_key: str | None = Header(default=None, alias="X-API-Key"),
) -> None:
    """Enforce optional API key auth for non-probe routes."""
    if request.method == "OPTIONS" or request.url.path in AUTH_EXEMPT_PATHS:
        return
    if not settings.api_key:
        return
    if x_api_key != settings.api_key:
        raise HTTPException(status_code=401, detail="api_key_invalid")

app = FastAPI(title="prompt-ops", version="0.1.0", dependencies=[Depends(_require_api_key)])

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.middleware("http")
async def request_guards(request: Request, call_next):
    """Enforce request guards and attach a correlation id for observability."""
    request_id = request.headers.get("X-Request-ID", str(uuid4()))
    request.state.request_id = request_id

    host_header = request.headers.get("host", "")
    if not is_allowed_host(host_header, settings.allowed_hosts):
        response = JSONResponse(
            status_code=400,
            content=_build_error_payload(request, code="host_not_allowed", message="host_not_allowed"),
        )
        response.headers["X-Request-ID"] = request_id
        return response

    if request.headers.get("content-length"):
        content_length = int(request.headers["content-length"])
        if content_length > settings.max_payload_bytes:
            response = JSONResponse(
                status_code=413,
                content=_build_error_payload(
                    request,
                    code="payload_too_large",
                    message="payload_too_large",
                ),
            )
            response.headers["X-Request-ID"] = request_id
            return response

    response = await call_next(request)
    response = apply_security_headers(response, settings.enable_hsts)
    response.headers["X-Request-ID"] = request_id
    return response


# Generated by GitHub Copilot
@app.exception_handler(StarletteHTTPException)
@app.exception_handler(HTTPException)
async def handle_http_exception(request: Request, exc: HTTPException) -> JSONResponse:
    """Return normalized error payloads for expected HTTP failures."""
    message = str(exc.detail) if exc.detail is not None else "request_failed"
    return JSONResponse(
        status_code=exc.status_code,
        content=_build_error_payload(
            request=request,
            code=_status_to_error_code(exc.status_code),
            message=message,
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(RequestValidationError)
async def handle_validation_exception(request: Request, exc: RequestValidationError) -> JSONResponse:
    """Return normalized payloads for input validation failures."""
    return JSONResponse(
        status_code=422,
        content=_build_error_payload(
            request=request,
            code="validation_error",
            message="request_validation_failed",
            details=exc.errors(),
        ),
    )


# Generated by GitHub Copilot
@app.exception_handler(Exception)
async def handle_unexpected_exception(request: Request, _: Exception) -> JSONResponse:
    """Return normalized payloads for unhandled internal errors."""
    return JSONResponse(
        status_code=500,
        content=_build_error_payload(
            request=request,
            code="internal_error",
            message="internal_server_error",
        ),
    )


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/ready")
def ready(response: Response) -> dict[str, str]:
    if not db_ready(settings.db_path):
        response.status_code = status.HTTP_503_SERVICE_UNAVAILABLE
        return {"status": "not_ready"}
    return {"status": "ready"}


# Generated by GitHub Copilot
@app.get("/healthz", include_in_schema=False)
def healthz() -> dict[str, str]:
    """Compatibility alias for health probes expecting /healthz."""
    return health()


# Generated by GitHub Copilot
@app.get("/readyz", include_in_schema=False)
def readyz(response: Response) -> dict[str, str]:
    """Compatibility alias for readiness probes expecting /readyz."""
    return ready(response)


@app.post("/api/v1/prompts", response_model=PromptVersion, status_code=status.HTTP_201_CREATED)
def create_prompt_version(payload: PromptCreateRequest) -> dict:
    row = build_prompt_row(payload)
    return create_prompt(settings.db_path, row)


@app.get("/api/v1/prompts", response_model=list[PromptVersion])
def fetch_prompts() -> list[dict]:
    return list_prompts(settings.db_path)


@app.post("/api/v1/experiments", response_model=ExperimentSummary, status_code=status.HTTP_201_CREATED)
def create_experiment_entry(payload: ExperimentCreateRequest) -> dict:
    if not prompt_exists(settings.db_path, payload.baseline_prompt_id):
        raise HTTPException(status_code=404, detail="baseline_prompt_not_found")
    if not prompt_exists(settings.db_path, payload.challenger_prompt_id):
        raise HTTPException(status_code=404, detail="challenger_prompt_not_found")

    row = build_experiment_row(payload)
    return create_experiment(settings.db_path, row)


@app.get("/api/v1/experiments", response_model=list[ExperimentSummary])
def fetch_experiments() -> list[dict]:
    return list_experiments(settings.db_path)


@app.get("/api/v1/experiments/{experiment_id}")
def fetch_experiment(experiment_id: str) -> dict:
    row = get_experiment(settings.db_path, experiment_id)
    if not row:
        raise HTTPException(status_code=404, detail="experiment_not_found")
    return row


@app.post("/api/v1/experiments/{experiment_id}/evaluate", response_model=EvaluateExperimentResponse)
def evaluate_experiment(experiment_id: str, payload: EvaluateExperimentRequest) -> dict:
    row = get_experiment(settings.db_path, experiment_id)
    if not row:
        raise HTTPException(status_code=404, detail="experiment_not_found")

    evaluation = evaluate_items(payload)
    update_experiment_evaluation(
        settings.db_path,
        experiment_id,
        evaluation["baseline_score"],
        evaluation["challenger_score"],
        evaluation["confidence_gap"],
        evaluation["winner_variant"],
        payload.model_dump(),
    )

    return {
        "experiment_id": experiment_id,
        "baseline_score": evaluation["baseline_score"],
        "challenger_score": evaluation["challenger_score"],
        "winner_variant": evaluation["winner_variant"],
        "confidence_gap": evaluation["confidence_gap"],
    }


@app.post("/api/v1/experiments/{experiment_id}/promote")
def promote_experiment_winner(experiment_id: str) -> dict[str, str]:
    experiment = get_experiment(settings.db_path, experiment_id)
    if not experiment:
        raise HTTPException(status_code=404, detail="experiment_not_found")

    promoted = promote_experiment(settings.db_path, experiment_id)
    if not promoted:
        raise HTTPException(status_code=409, detail="winner_required_before_promotion")

    return {"status": "promoted"}
