# Generated by GitHub Copilot
from fastapi import Request, Response


# Generated by GitHub Copilot
"""Check whether a request host is in the runtime allowlist."""
def is_allowed_host(host_header: str, allowed_hosts: set[str]) -> bool:
    if "*" in allowed_hosts:
        return True
    host = host_header.split(":")[0].lower()
    return host in {item.lower() for item in allowed_hosts}


# Generated by GitHub Copilot
"""Apply baseline HTTP security headers for browser and API traffic."""
def apply_security_headers(response: Response, enable_hsts: bool) -> Response:
    response.headers["X-Content-Type-Options"] = "nosniff"
    response.headers["X-Frame-Options"] = "DENY"
    response.headers["Referrer-Policy"] = "same-origin"
    response.headers["X-XSS-Protection"] = "0"

    if enable_hsts:
        response.headers["Strict-Transport-Security"] = "max-age=31536000; includeSubDomains"

    return response
