# Generated by GitHub Copilot
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class PromptCreateRequest(BaseModel):
    name: str = Field(min_length=1, max_length=120)
    version: str = Field(min_length=1, max_length=40)
    content: str = Field(min_length=1, max_length=12000)
    variables: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)


class PromptVersion(BaseModel):
    prompt_id: str
    created_at: datetime
    name: str
    version: str
    content: str
    variables: list[str]
    tags: list[str]


class ExperimentCreateRequest(BaseModel):
    name: str = Field(min_length=1, max_length=140)
    baseline_prompt_id: str = Field(min_length=1, max_length=64)
    challenger_prompt_id: str = Field(min_length=1, max_length=64)
    traffic_split_baseline: float = Field(default=0.5, ge=0.05, le=0.95)


class ExperimentSummary(BaseModel):
    experiment_id: str
    created_at: datetime
    name: str
    baseline_prompt_id: str
    challenger_prompt_id: str
    traffic_split_baseline: float
    status: str
    baseline_score: float
    challenger_score: float
    winner_variant: str | None


class EvaluationItem(BaseModel):
    variant: Literal["baseline", "challenger"]
    quality_score: float = Field(ge=0.0, le=1.0)
    latency_ms: float = Field(ge=0.0)
    safety_pass: bool


class EvaluateExperimentRequest(BaseModel):
    items: list[EvaluationItem] = Field(min_length=2)


class EvaluateExperimentResponse(BaseModel):
    experiment_id: str
    baseline_score: float
    challenger_score: float
    winner_variant: str | None
    confidence_gap: float
