# Generated by GitHub Copilot
from datetime import datetime, timezone
from statistics import mean
from uuid import uuid4

from .models import EvaluateExperimentRequest, ExperimentCreateRequest, PromptCreateRequest


# Generated by GitHub Copilot
"""Build a persisted prompt row from a validated create request."""
def build_prompt_row(request: PromptCreateRequest) -> dict:
    return {
        "prompt_id": str(uuid4()),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "name": request.name,
        "version": request.version,
        "content": request.content,
        "variables": request.variables,
        "tags": request.tags,
    }


# Generated by GitHub Copilot
"""Build initial experiment row before evaluations are recorded."""
def build_experiment_row(request: ExperimentCreateRequest) -> dict:
    return {
        "experiment_id": str(uuid4()),
        "created_at": datetime.now(timezone.utc).isoformat(),
        "name": request.name,
        "baseline_prompt_id": request.baseline_prompt_id,
        "challenger_prompt_id": request.challenger_prompt_id,
        "traffic_split_baseline": request.traffic_split_baseline,
        "status": "draft",
        "winner_variant": None,
        "baseline_score": 0.0,
        "challenger_score": 0.0,
        "confidence_gap": 0.0,
        "evaluation_payload": {},
    }


# Generated by GitHub Copilot
"""Score a single evaluation item using deterministic weighted criteria."""
def score_item(quality_score: float, latency_ms: float, safety_pass: bool) -> float:
    latency_component = 1.0 / (1.0 + (latency_ms / 1000.0))
    safety_component = 1.0 if safety_pass else 0.0

    weighted = (quality_score * 0.6) + (latency_component * 0.2) + (safety_component * 0.2)
    return max(0.0, min(1.0, weighted))


# Generated by GitHub Copilot
"""Aggregate baseline and challenger item scores and determine winner variant."""
def evaluate_items(payload: EvaluateExperimentRequest) -> dict:
    baseline_scores: list[float] = []
    challenger_scores: list[float] = []

    for item in payload.items:
        item_score = score_item(item.quality_score, item.latency_ms, item.safety_pass)
        if item.variant == "baseline":
            baseline_scores.append(item_score)
        else:
            challenger_scores.append(item_score)

    if not baseline_scores or not challenger_scores:
        raise ValueError("Both baseline and challenger evaluation items are required")

    baseline_score = mean(baseline_scores)
    challenger_score = mean(challenger_scores)
    confidence_gap = abs(challenger_score - baseline_score)

    winner_variant: str | None = None
    if confidence_gap >= 0.02:
        winner_variant = "challenger" if challenger_score > baseline_score else "baseline"

    return {
        "baseline_score": baseline_score,
        "challenger_score": challenger_score,
        "confidence_gap": confidence_gap,
        "winner_variant": winner_variant,
    }
