# Generated by GitHub Copilot
import json
import os
import sqlite3
from contextlib import closing
from typing import Any


CREATE_PROMPTS_TABLE = """
CREATE TABLE IF NOT EXISTS prompts (
    prompt_id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    name TEXT NOT NULL,
    version TEXT NOT NULL,
    content TEXT NOT NULL,
    variables_json TEXT NOT NULL,
    tags_json TEXT NOT NULL
)
"""

CREATE_EXPERIMENTS_TABLE = """
CREATE TABLE IF NOT EXISTS experiments (
    experiment_id TEXT PRIMARY KEY,
    created_at TEXT NOT NULL,
    name TEXT NOT NULL,
    baseline_prompt_id TEXT NOT NULL,
    challenger_prompt_id TEXT NOT NULL,
    traffic_split_baseline REAL NOT NULL,
    status TEXT NOT NULL,
    winner_variant TEXT,
    baseline_score REAL NOT NULL,
    challenger_score REAL NOT NULL,
    confidence_gap REAL NOT NULL,
    evaluation_payload_json TEXT NOT NULL
)
"""


# Generated by GitHub Copilot
"""Initialize persistent sqlite schema and parent directory if needed."""
def init_db(db_path: str) -> None:
    parent = os.path.dirname(db_path)
    if parent:
        os.makedirs(parent, exist_ok=True)

    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(CREATE_PROMPTS_TABLE)
            cursor.execute(CREATE_EXPERIMENTS_TABLE)
        connection.commit()


# Generated by GitHub Copilot
"""Perform a lightweight DB connectivity check for readiness probes."""
def db_ready(db_path: str) -> bool:
    try:
        with closing(sqlite3.connect(db_path)) as connection:
            with closing(connection.cursor()) as cursor:
                cursor.execute("SELECT 1")
                cursor.fetchone()
        return True
    except sqlite3.Error:
        return False


# Generated by GitHub Copilot
"""Insert prompt version row and return the persisted prompt object."""
def create_prompt(db_path: str, row: dict[str, Any]) -> dict[str, Any]:
    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                INSERT INTO prompts (prompt_id, created_at, name, version, content, variables_json, tags_json)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    row["prompt_id"],
                    row["created_at"],
                    row["name"],
                    row["version"],
                    row["content"],
                    json.dumps(row["variables"], separators=(",", ":"), ensure_ascii=True),
                    json.dumps(row["tags"], separators=(",", ":"), ensure_ascii=True),
                ),
            )
        connection.commit()

    return row


# Generated by GitHub Copilot
"""Return prompt versions ordered by creation time descending."""
def list_prompts(db_path: str, limit: int = 50) -> list[dict[str, Any]]:
    with closing(sqlite3.connect(db_path)) as connection:
        connection.row_factory = sqlite3.Row
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                SELECT prompt_id, created_at, name, version, content, variables_json, tags_json
                FROM prompts
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (limit,),
            )
            rows = cursor.fetchall()

    result: list[dict[str, Any]] = []
    for row in rows:
        prompt = dict(row)
        prompt["variables"] = json.loads(prompt.pop("variables_json"))
        prompt["tags"] = json.loads(prompt.pop("tags_json"))
        result.append(prompt)

    return result


# Generated by GitHub Copilot
"""Check whether a prompt ID exists before creating experiments."""
def prompt_exists(db_path: str, prompt_id: str) -> bool:
    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute("SELECT 1 FROM prompts WHERE prompt_id = ? LIMIT 1", (prompt_id,))
            row = cursor.fetchone()
    return row is not None


# Generated by GitHub Copilot
"""Insert a new experiment row and return the experiment summary."""
def create_experiment(db_path: str, row: dict[str, Any]) -> dict[str, Any]:
    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                INSERT INTO experiments (
                    experiment_id, created_at, name, baseline_prompt_id, challenger_prompt_id,
                    traffic_split_baseline, status, winner_variant, baseline_score,
                    challenger_score, confidence_gap, evaluation_payload_json
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    row["experiment_id"],
                    row["created_at"],
                    row["name"],
                    row["baseline_prompt_id"],
                    row["challenger_prompt_id"],
                    row["traffic_split_baseline"],
                    row["status"],
                    row["winner_variant"],
                    row["baseline_score"],
                    row["challenger_score"],
                    row["confidence_gap"],
                    json.dumps(row["evaluation_payload"], separators=(",", ":"), ensure_ascii=True),
                ),
            )
        connection.commit()

    return row


# Generated by GitHub Copilot
"""Return experiment summaries ordered by newest first."""
def list_experiments(db_path: str, limit: int = 50) -> list[dict[str, Any]]:
    with closing(sqlite3.connect(db_path)) as connection:
        connection.row_factory = sqlite3.Row
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                SELECT experiment_id, created_at, name, baseline_prompt_id, challenger_prompt_id,
                       traffic_split_baseline, status, winner_variant, baseline_score,
                       challenger_score, confidence_gap
                FROM experiments
                ORDER BY created_at DESC
                LIMIT ?
                """,
                (limit,),
            )
            rows = cursor.fetchall()

    return [dict(row) for row in rows]


# Generated by GitHub Copilot
"""Fetch a single experiment including stored evaluation payload snapshot."""
def get_experiment(db_path: str, experiment_id: str) -> dict[str, Any] | None:
    with closing(sqlite3.connect(db_path)) as connection:
        connection.row_factory = sqlite3.Row
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                SELECT experiment_id, created_at, name, baseline_prompt_id, challenger_prompt_id,
                       traffic_split_baseline, status, winner_variant, baseline_score,
                       challenger_score, confidence_gap, evaluation_payload_json
                FROM experiments
                WHERE experiment_id = ?
                LIMIT 1
                """,
                (experiment_id,),
            )
            row = cursor.fetchone()

    if not row:
        return None

    result = dict(row)
    result["evaluation_payload"] = json.loads(result.pop("evaluation_payload_json"))
    return result


# Generated by GitHub Copilot
"""Persist evaluation scores and winner decision for an existing experiment."""
def update_experiment_evaluation(
    db_path: str,
    experiment_id: str,
    baseline_score: float,
    challenger_score: float,
    confidence_gap: float,
    winner_variant: str | None,
    evaluation_payload: dict[str, Any],
) -> None:
    status = "evaluated"
    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                UPDATE experiments
                SET status = ?, winner_variant = ?, baseline_score = ?, challenger_score = ?,
                    confidence_gap = ?, evaluation_payload_json = ?
                WHERE experiment_id = ?
                """,
                (
                    status,
                    winner_variant,
                    baseline_score,
                    challenger_score,
                    confidence_gap,
                    json.dumps(evaluation_payload, separators=(",", ":"), ensure_ascii=True),
                    experiment_id,
                ),
            )
        connection.commit()


# Generated by GitHub Copilot
"""Mark an experiment as promoted if it has a winner variant."""
def promote_experiment(db_path: str, experiment_id: str) -> bool:
    with closing(sqlite3.connect(db_path)) as connection:
        with closing(connection.cursor()) as cursor:
            cursor.execute(
                """
                UPDATE experiments
                SET status = 'promoted'
                WHERE experiment_id = ? AND winner_variant IS NOT NULL
                """,
                (experiment_id,),
            )
            updated = cursor.rowcount
        connection.commit()

    return updated > 0
