// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from "react";

import { MetricTile } from "./components/MetricTile";
import {
    createExperiment,
    createPrompt,
    evaluateExperiment,
    fetchExperiments,
    fetchPrompts,
    promoteExperiment,
    type ExperimentSummary,
    type PromptVersion,
} from "./lib/api";

const DEFAULT_EVAL_PAYLOAD = {
    items: [
        { variant: "baseline" as const, quality_score: 0.76, latency_ms: 910, safety_pass: true },
        { variant: "challenger" as const, quality_score: 0.84, latency_ms: 790, safety_pass: true },
    ],
};

// Generated by GitHub Copilot
/** Render prompt and experiment operations dashboard with promotion flow controls. */
export default function App(): JSX.Element {
    const [prompts, setPrompts] = useState<PromptVersion[]>([]);
    const [experiments, setExperiments] = useState<ExperimentSummary[]>([]);
    const [selectedExperimentId, setSelectedExperimentId] = useState<string>("");
    const [evaluationInput, setEvaluationInput] = useState(JSON.stringify(DEFAULT_EVAL_PAYLOAD, null, 2));
    const [error, setError] = useState<string | null>(null);
    const [message, setMessage] = useState<string | null>(null);

    const [promptForm, setPromptForm] = useState({
        name: "support_refund_prompt",
        version: "v1",
        content: "You are a support agent. Follow policy and cite policy sections.",
        variables: "customer_tier,region",
        tags: "support,refund",
    });

    const [experimentForm, setExperimentForm] = useState({
        name: "refund_policy_ab",
        baseline_prompt_id: "",
        challenger_prompt_id: "",
        traffic_split_baseline: "0.50",
    });

    useEffect(() => {
        void refreshData();
    }, []);

    // Generated by GitHub Copilot
    /** Refresh prompt and experiment collections from backend APIs. */
    async function refreshData(): Promise<void> {
        try {
            const [promptRows, experimentRows] = await Promise.all([fetchPrompts(), fetchExperiments()]);
            setPrompts(promptRows);
            setExperiments(experimentRows);

            if (!selectedExperimentId && experimentRows.length > 0) {
                setSelectedExperimentId(experimentRows[0].experiment_id);
            }
        } catch (apiError) {
            setError(apiError instanceof Error ? apiError.message : "Failed to refresh data");
        }
    }

    // Generated by GitHub Copilot
    /** Submit prompt version form and auto-refresh prompt catalog. */
    async function onCreatePrompt(): Promise<void> {
        setError(null);
        setMessage(null);
        try {
            await createPrompt({
                name: promptForm.name,
                version: promptForm.version,
                content: promptForm.content,
                variables: promptForm.variables.split(",").map((item) => item.trim()).filter(Boolean),
                tags: promptForm.tags.split(",").map((item) => item.trim()).filter(Boolean),
            });
            setMessage("Prompt version created.");
            await refreshData();
        } catch (apiError) {
            setError(apiError instanceof Error ? apiError.message : "Failed to create prompt");
        }
    }

    // Generated by GitHub Copilot
    /** Create baseline/challenger experiment from selected prompt IDs. */
    async function onCreateExperiment(): Promise<void> {
        setError(null);
        setMessage(null);
        try {
            const created = await createExperiment({
                name: experimentForm.name,
                baseline_prompt_id: experimentForm.baseline_prompt_id,
                challenger_prompt_id: experimentForm.challenger_prompt_id,
                traffic_split_baseline: Number(experimentForm.traffic_split_baseline),
            });
            setSelectedExperimentId(created.experiment_id);
            setMessage("Experiment created.");
            await refreshData();
        } catch (apiError) {
            setError(apiError instanceof Error ? apiError.message : "Failed to create experiment");
        }
    }

    // Generated by GitHub Copilot
    /** Evaluate currently selected experiment using JSON input payload. */
    async function onEvaluateExperiment(): Promise<void> {
        if (!selectedExperimentId) {
            setError("Select an experiment first.");
            return;
        }

        setError(null);
        setMessage(null);
        try {
            const payload = JSON.parse(evaluationInput) as typeof DEFAULT_EVAL_PAYLOAD;
            const result = await evaluateExperiment(selectedExperimentId, payload);
            setMessage(
                result.winner_variant
                    ? `Evaluation complete. Winner: ${result.winner_variant}`
                    : "Evaluation complete. No confident winner yet."
            );
            await refreshData();
        } catch (apiError) {
            setError(apiError instanceof Error ? apiError.message : "Failed to evaluate experiment");
        }
    }

    // Generated by GitHub Copilot
    /** Promote winner for currently selected experiment if eligible. */
    async function onPromote(): Promise<void> {
        if (!selectedExperimentId) {
            setError("Select an experiment first.");
            return;
        }

        setError(null);
        setMessage(null);
        try {
            await promoteExperiment(selectedExperimentId);
            setMessage("Experiment promoted.");
            await refreshData();
        } catch (apiError) {
            setError(apiError instanceof Error ? apiError.message : "Failed to promote experiment");
        }
    }

    const selectedExperiment = useMemo(
        () => experiments.find((item) => item.experiment_id === selectedExperimentId) || null,
        [experiments, selectedExperimentId]
    );

    const summaryTiles = useMemo(() => {
        if (!selectedExperiment) {
            return [];
        }

        return [
            { label: "Status", value: selectedExperiment.status },
            { label: "Baseline Score", value: selectedExperiment.baseline_score.toFixed(3) },
            { label: "Challenger Score", value: selectedExperiment.challenger_score.toFixed(3) },
            {
                label: "Winner",
                value: selectedExperiment.winner_variant ?? "No winner",
                hint: `Traffic baseline ${Math.round(selectedExperiment.traffic_split_baseline * 100)}%`,
            },
        ];
    }, [selectedExperiment]);

    return (
        <main className="page">
            <header className="hero" aria-labelledby="title">
                <h1 id="title">prompt-ops command center</h1>
                <p>Version prompts, run baseline/challenger evaluations, and promote with confidence.</p>
            </header>

            <section className="panel" aria-labelledby="prompt-title">
                <h2 id="prompt-title">Create Prompt Version</h2>
                <div className="grid-2">
                    <label>
                        Name
                        <input value={promptForm.name} onChange={(event) => setPromptForm({ ...promptForm, name: event.target.value })} />
                    </label>
                    <label>
                        Version
                        <input value={promptForm.version} onChange={(event) => setPromptForm({ ...promptForm, version: event.target.value })} />
                    </label>
                </div>
                <label>
                    Prompt Content
                    <textarea rows={4} value={promptForm.content} onChange={(event) => setPromptForm({ ...promptForm, content: event.target.value })} />
                </label>
                <div className="grid-2">
                    <label>
                        Variables (comma-separated)
                        <input value={promptForm.variables} onChange={(event) => setPromptForm({ ...promptForm, variables: event.target.value })} />
                    </label>
                    <label>
                        Tags (comma-separated)
                        <input value={promptForm.tags} onChange={(event) => setPromptForm({ ...promptForm, tags: event.target.value })} />
                    </label>
                </div>
                <button type="button" onClick={() => void onCreatePrompt()}>Create Prompt</button>
            </section>

            <section className="panel" aria-labelledby="experiment-title">
                <h2 id="experiment-title">Create Experiment</h2>
                <div className="grid-2">
                    <label>
                        Experiment Name
                        <input
                            value={experimentForm.name}
                            onChange={(event) => setExperimentForm({ ...experimentForm, name: event.target.value })}
                        />
                    </label>
                    <label>
                        Traffic Split Baseline
                        <input
                            value={experimentForm.traffic_split_baseline}
                            onChange={(event) => setExperimentForm({ ...experimentForm, traffic_split_baseline: event.target.value })}
                        />
                    </label>
                </div>
                <div className="grid-2">
                    <label>
                        Baseline Prompt
                        <select
                            value={experimentForm.baseline_prompt_id}
                            onChange={(event) => setExperimentForm({ ...experimentForm, baseline_prompt_id: event.target.value })}
                        >
                            <option value="">Select baseline</option>
                            {prompts.map((prompt) => (
                                <option key={prompt.prompt_id} value={prompt.prompt_id}>
                                    {prompt.name}:{prompt.version}
                                </option>
                            ))}
                        </select>
                    </label>
                    <label>
                        Challenger Prompt
                        <select
                            value={experimentForm.challenger_prompt_id}
                            onChange={(event) => setExperimentForm({ ...experimentForm, challenger_prompt_id: event.target.value })}
                        >
                            <option value="">Select challenger</option>
                            {prompts.map((prompt) => (
                                <option key={prompt.prompt_id} value={prompt.prompt_id}>
                                    {prompt.name}:{prompt.version}
                                </option>
                            ))}
                        </select>
                    </label>
                </div>
                <button type="button" onClick={() => void onCreateExperiment()}>Create Experiment</button>
            </section>

            <section className="panel" aria-labelledby="evaluate-title">
                <h2 id="evaluate-title">Evaluate and Promote</h2>
                <label>
                    Experiment
                    <select value={selectedExperimentId} onChange={(event) => setSelectedExperimentId(event.target.value)}>
                        <option value="">Select experiment</option>
                        {experiments.map((experiment) => (
                            <option key={experiment.experiment_id} value={experiment.experiment_id}>
                                {experiment.name} ({experiment.status})
                            </option>
                        ))}
                    </select>
                </label>
                <label>
                    Evaluation Payload (JSON)
                    <textarea rows={10} value={evaluationInput} onChange={(event) => setEvaluationInput(event.target.value)} spellCheck={false} />
                </label>
                <div className="actions">
                    <button type="button" onClick={() => void onEvaluateExperiment()}>Run Evaluation</button>
                    <button type="button" onClick={() => void onPromote()} className="secondary">Promote Winner</button>
                    <button type="button" onClick={() => void refreshData()} className="secondary">Refresh</button>
                </div>

                {message ? <p className="ok" role="status">{message}</p> : null}
                {error ? <p className="error" role="alert">{error}</p> : null}
            </section>

            <section className="panel" aria-labelledby="summary-title">
                <h2 id="summary-title">Selected Experiment Summary</h2>
                {!selectedExperiment ? <p className="muted">Select an experiment to view metrics.</p> : null}
                <div className="tile-grid">
                    {summaryTiles.map((tile) => (
                        <MetricTile key={tile.label} label={tile.label} value={tile.value} hint={tile.hint} />
                    ))}
                </div>
            </section>
        </main>
    );
}
