// Generated by GitHub Copilot
export interface PromptVersion {
  prompt_id: string;
  created_at: string;
  name: string;
  version: string;
  content: string;
  variables: string[];
  tags: string[];
}

export interface ExperimentSummary {
  experiment_id: string;
  created_at: string;
  name: string;
  baseline_prompt_id: string;
  challenger_prompt_id: string;
  traffic_split_baseline: number;
  status: string;
  baseline_score: number;
  challenger_score: number;
  winner_variant: string | null;
}

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:8020";

// Generated by GitHub Copilot
/** Create a new prompt version in prompt registry storage. */
export async function createPrompt(payload: {
  name: string;
  version: string;
  content: string;
  variables: string[];
  tags: string[];
}): Promise<PromptVersion> {
  const response = await fetch(`${API_BASE_URL}/api/v1/prompts`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    throw new Error("Failed to create prompt");
  }

  return (await response.json()) as PromptVersion;
}

// Generated by GitHub Copilot
/** Fetch registered prompt versions ordered by newest first. */
export async function fetchPrompts(): Promise<PromptVersion[]> {
  const response = await fetch(`${API_BASE_URL}/api/v1/prompts`);
  if (!response.ok) {
    throw new Error("Failed to fetch prompts");
  }
  return (await response.json()) as PromptVersion[];
}

// Generated by GitHub Copilot
/** Create a new A/B experiment linking baseline and challenger prompt versions. */
export async function createExperiment(payload: {
  name: string;
  baseline_prompt_id: string;
  challenger_prompt_id: string;
  traffic_split_baseline: number;
}): Promise<ExperimentSummary> {
  const response = await fetch(`${API_BASE_URL}/api/v1/experiments`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const details = await response.json().catch(() => ({ detail: "Failed to create experiment" }));
    throw new Error(details.detail || "Failed to create experiment");
  }

  return (await response.json()) as ExperimentSummary;
}

// Generated by GitHub Copilot
/** Fetch experiment list for leaderboard and promotion workflow visibility. */
export async function fetchExperiments(): Promise<ExperimentSummary[]> {
  const response = await fetch(`${API_BASE_URL}/api/v1/experiments`);
  if (!response.ok) {
    throw new Error("Failed to fetch experiments");
  }
  return (await response.json()) as ExperimentSummary[];
}

// Generated by GitHub Copilot
/** Submit evaluation items and return winner summary for one experiment. */
export async function evaluateExperiment(
  experimentId: string,
  payload: { items: Array<{ variant: "baseline" | "challenger"; quality_score: number; latency_ms: number; safety_pass: boolean }> }
): Promise<{ experiment_id: string; baseline_score: number; challenger_score: number; winner_variant: string | null; confidence_gap: number }> {
  const response = await fetch(`${API_BASE_URL}/api/v1/experiments/${experimentId}/evaluate`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(payload),
  });

  if (!response.ok) {
    const details = await response.json().catch(() => ({ detail: "Failed to evaluate experiment" }));
    throw new Error(details.detail || "Failed to evaluate experiment");
  }

  return (await response.json()) as {
    experiment_id: string;
    baseline_score: number;
    challenger_score: number;
    winner_variant: string | null;
    confidence_gap: number;
  };
}

// Generated by GitHub Copilot
/** Promote evaluated winner for a completed experiment. */
export async function promoteExperiment(experimentId: string): Promise<void> {
  const response = await fetch(`${API_BASE_URL}/api/v1/experiments/${experimentId}/promote`, {
    method: "POST",
  });

  if (!response.ok) {
    const details = await response.json().catch(() => ({ detail: "Failed to promote experiment" }));
    throw new Error(details.detail || "Failed to promote experiment");
  }
}
